Metrics/CyclomaticComplexity:
  Enabled: false

Lint/NotNil:
  Enabled: false

Style/NegatedConditionsInUnless:
  Enabled: false

Performance/AnyInsteadOfEmpty:
  Enabled: true
  Excluded:
    - src/marten/db/management/migrations/reader.cr

Layout/LineLength:
  Enabled: true
  MaxLength: 120
